/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_dongledial_Call */

#ifndef _Included_com_example_dongledial_Call
#define _Included_com_example_dongledial_Call
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dongledial_Call
 * Method:    dial
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_dongledial_Call_dial
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
